language: node_js
node_js:
- "6"

# Build the app and a docker image
script:
- npm run build
- docker build -t ${TRAVIS_COMMIT} --build-arg KILLRVIDEO_YOUTUBE_API_KEY=$KILLRVIDEO_YOUTUBE_API_KEY .

# If successful, see if we need to publish also
after_success:
- test -z $TRAVIS_TAG && travis_terminate 0
- docker tag ${TRAVIS_COMMIT} killrvideo/killrvideo-generator:${TRAVIS_TAG}
- docker login -u $DOCKER_USER -p $DOCKER_PASS
- docker push killrvideo/killrvideo-generator:${TRAVIS_TAG}
- "[ \"$(git tag --sort=-v:refname | grep -P \"^\\d+.\\d+.\\d+$\" | head -n1)\" == \"$TRAVIS_TAG\" ] && { docker tag ${TRAVIS_COMMIT} killrvideo/killrvideo-generator:latest; docker push killrvideo/killrvideo-generator:latest; }"
- "[ \"$(git tag --sort=-v:refname | grep -P \"^\\d+.\\d+.\\d+$\" | head -n1)\" == \"$TRAVIS_TAG\" ] && { docker tag ${TRAVIS_COMMIT} killrvideo/killrvideo-generator:$(echo $TRAVIS_TAG | cut -d'.' -f 1); docker push killrvideo/killrvideo-generator:$(echo $TRAVIS_TAG | cut -d'.' -f 1); }"
- "[ \"$(git tag --sort=-v:refname | grep -P \"^\\d+.\\d+.\\d+$\" | head -n1)\" == \"$TRAVIS_TAG\" ] && { docker tag ${TRAVIS_COMMIT} killrvideo/killrvideo-generator:$(echo $TRAVIS_TAG | cut -d'.' -f 1).$(echo $TRAVIS_TAG | cut -d'.' -f 2); docker push killrvideo/killrvideo-generator:$(echo $TRAVIS_TAG | cut -d'.' -f 1).$(echo $TRAVIS_TAG | cut -d'.' -f 2); }"

# Sudo required for doing docker build
sudo: required
services:
- docker

env:
  global:
  # Needed to compile native modules
  - CXX=g++-4.8
  # DOCKER_USER
  - secure: hL9GzKnAuHP130bLzB1nK9eF6bfPD4yFdQ1IdRRp7QDZ+AJ2MUw483w5Uacw6/VNk+KlItO9ySxkAI8gaBcxjxcp+TmFkmD0o4rRQixCoZiqlNeTCMmkx5J6KffNALiFBFPjOvVNXLEYh6lbyIsPJR0/eHGlhCbfpx9Ok9PxzVV4AtNNXVcqCl4hZFWPU8OX7nL0pyQ86MD1WiC/1nfTaE/9zaZ8M/qJhv558KmsSXnFN1eGrwVJLt8XPbZ5aKEvJq3cngwVJ3/hmMQnA6ScgANZFbFrDZo9gDmQLDAbGzQ4mg1wpmvdCGB9HEo14o+ZK3utmnURZDGLHcbgKitIp7fd+FyIktxF3h+hYm7yMV/P67ixLXWxay9F0XXkKF1CPhRU+uEijcWQY/txUItvfHJtDGQbHhChUPmzv2eTQD5QoevFByZ6c3ekQew6hgCPaOsV2FspQQ+XVtdjiiOzmWzeFux2Obc46K85BSyeEp9SjuTJ0772dFBZjWn9UP+M5B8THs4BNPhkSVhceHQBvv65H8DZYEazue0aJYwJhMd1qx5tq/3dXItyDVqxCj0J0LFI4TsFbSf4R+snYOxjc2dkpO1l9aZyLNBTbRn//MTki8o/tdIjAzNYKKWHHBWCYN7OU4Ej4t7XI/SKs3Wf131ebqLlTYU0ppJD7KQUvCU=
  # DOCKER_PASS
  - secure: hxakhOfACkkXcGc5T9cT0+a+ICw6X2ybsOXzJsgdju4QbdP0nD2iBSZCypDzfdzlF/y83yJGcSznegMega37ABomPd8BF04IJTY1ZSvfj8LiUiLLfo/YSsz68r/X1G/AxVmS/7x9x5xaCPMnCHaH2jK5Qiogawzlqgqw/h3EAQlnJyKdjwwmFpATUAuRJidQ/95pn4KYvERg3eZ7/DzqbAO4IRjSuxHRNqDsHXDR4xlBxXAwqt0SE9qfr8rIbuA264vwStltPi4RDfTWWBooxFTGWHpu7rS/N1xEg7+48Il0zckVqmbwMJeAfl8abXhqK5RRrpv77icHeqxi5bev/SL28PnNOhj5gXn6a4/1/JPuhzmKp1omNtlJsjjZhs7YidSOVQ2nEJjDoeQ9/d+Z+g6DosnkDbiS7+ijvIPD9SlRbyUlf7Z3wD8Hf91/fUgkaUoIVkBUFvW8i0fArfcWSIQErvixIGhj41yNOwIAheUFM4Y39NsuilJZZmqZ2Zh0/9AHUiY4fA7C6CajFC06CpjUCpDhb3m0uy1vJcUiG7Y3J6iTrRzaW8eqPnGBQcVTS7/dXPj3WtEP/xOF93sYeZMKE7hk489WAUJNLV9kmasSaVTzbu80kfM5Ml9m675dN3ztUAhaAPT0IqHnycngMBKe2Y7+EDalsDBsffOpO0k=
  # KILLRVIDEO_YOUTUBE_API_KEY
  - secure: l2zG4e5N1j0ttF7p9sV9PyN7eid/iBPYV4hvXu05SmooIgKEdHQkX932UORGo1ZuLDz5NqBwsQD7xyt0RJ/Rx3aNGORauYUxrLjA+waFfi+d3Xv/4LTqjcU2C5SdVn8K/8GwXGq70RrmcjWDfAUl+By9rrvAjdKISJuptgn/DCgmdbM9tlvdQ9jEpRF+EdArh5nxdTQVe0Qh0IRItPceaGLB5YS6ilpmOx/GNz8C78Vy+1rHJev1cekON7O6I5ziU2cNtUR3hr0v55F/DD1EbvsXwptXWV/Pb5FWINmNfX9UrIPeq0XkqIqfbPnVVWlMc35uzwjVzp2yrp6LO1sVIni8/BFIG7bPr75KpNix0UlTAUdjUHomum4M+z8zle6o2CMfJZmKIXvIY4stwrZvO5TvjKQsVDrcednRIhqxAHCWvq0AGVbStEYuWw81VuHE+trud1wDPy+uB9Z65UZSrNGPxAdCFQUeCmtjspkt93AT/mN02hE1VyQ2s6IIRHqqKiUhTzRPsZPrtJ9X29lQUJa8NYonQUnWAQ05ApetZ6D9g7g9CFAuTfdpI1kZ00F0nhVZ++QDhcHaPKCUTjKDG3rKWuUqR//yEV9wftVjYRyWcyQXriw/0zeOGI5z5yQxplmH0rLP0QIhrE/OsDhy4gUNGLhdsqLW3cUIAWtQF1w=
# Also needed to compile native modules
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-4.8

# Cache node_modules between builds to try and speed things up
cache:
  directories:
  - node_modules

notifications:
  slack:
    rooms:
      secure: YhUaJqbOPyvalHUgyQQ4q34qjRlDPm17DAGEo2GcK7g3oC97kAZaLj1Z6EI37hr/TrJH+QkH2mrFhJohisVmYIn3xSrseaD5WUyMY0dFV4PKTyPB+fAyR4M03CG1kqrVEdspyPNQRJ9er30Nf3246IRHM44tq/M5LkT3U0S6wenZh1WmPtRjUHxupPeD2ByfHJ1pc7LnxwvVGc5o2FcRf+gAL9GWYwrDCMHShL4LmY3iqkEScVbaineg1azxwsnPhmhc4Yv9rQlRqSACl1veH6k9xNZfufOCykKc1j7/Qykt2RrxwyHLANusBzaG018tNt6iR/NJ27xModmCjDdoFd9xM97dw38Pj6ZyF/FNJjgKNz+nvVcPYOCKg8shx+rWtXADAQPDbhDXOAeMrnj2WsYlW2ZDdfU4tLXH4IeLKfPitUetuFvAUuURk9XiHprOqRZBtP3vZqum36q2p598DMWcmpKFPMdEeTZPksrLchEp1+Yid1qVYwZc2f3BQEBNZdkPcpRltxddS0NP1XVlIbTm5dZhej5TIon4c9zSRAXjjykmZVz0q/9vOJ7jB+XLAL+DgPYgHqT/GtS6hoML5x5efNFPsY8Aq2WgAWlCJrewfeIPpXmNL7Idz1o8A+DCf+R2lF6ravZMi6KNSvwHdc1h6KOjcMXPrpmWr56tWEQ=
